#!/usr/bin/env python3
"""Batch insert articles from scout retrieval run."""
import subprocess
import json
import sys
from datetime import datetime

DB = "/paperclip/agents/db.py"
NOW = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")

articles = [
    # CleanTechnica
    {"url":"https://cleantechnica.com/2026/04/07/trump-is-losing-the-war-on-evs-as-new-incentives-kick-in/","title":"Trump Is Losing The War On EVs As New Incentives Kick In","summary":"Uber expands its $4,000 EV incentive program nationwide to help consumers offset lost federal tax credits.","source_name":"CleanTechnica","domain":"cleantechnica.com","published_at":"2026-04-07T17:29:33Z"},
    {"url":"https://cleantechnica.com/2026/04/07/battery-energy-storage-key-to-india-emissions-reduction-goal/","title":"Battery Energy Storage Key To India Emissions Reduction Goal","summary":"India commits to renewable energy and battery storage systems targeting carbon neutrality by 2070.","source_name":"CleanTechnica","domain":"cleantechnica.com","published_at":"2026-04-07T16:23:12Z"},
    {"url":"https://cleantechnica.com/2026/04/07/op-ed-chinese-ev-brands-overwhelm-the-manila-auto-show-2026/","title":"Op-Ed: Chinese EV Brands Overwhelm The Manila Auto Show 2026","summary":"The Manila auto show features expanded exhibition space with significantly increased electrification presence.","source_name":"CleanTechnica","domain":"cleantechnica.com","published_at":"2026-04-07T15:13:52Z"},
    {"url":"https://cleantechnica.com/2026/04/07/trump-breathes-new-life-into-old-green-hydrogen-dreams/","title":"Trump Breathes New Life Into Old Green Hydrogen Dreams","summary":"Japan explores green hydrogen alliances and plans a hydrogen truck freight corridor in response to geopolitical shifts.","source_name":"CleanTechnica","domain":"cleantechnica.com","published_at":"2026-04-07T15:10:22Z"},
    {"url":"https://cleantechnica.com/2026/04/07/51-million-in-new-ev-charger-funding-available-in-michigan/","title":"$51 Million In New EV Charger Funding Available In Michigan","summary":"Michigan receives NEVI funds to expand electric vehicle charging infrastructure across the state.","source_name":"CleanTechnica","domain":"cleantechnica.com","published_at":"2026-04-07T13:54:35Z"},
    {"url":"https://cleantechnica.com/2026/04/06/coming-to-you-from-big-oil-profits-the-vermont-climate-superfund/","title":"Coming To You From Big Oil Profits: The Vermont Climate Superfund","summary":"Vermont's climate recovery law aims to collect damages from fossil fuel industries for climate adaptation projects.","source_name":"CleanTechnica","domain":"cleantechnica.com","published_at":"2026-04-07T03:55:35Z"},
    {"url":"https://cleantechnica.com/2026/04/06/honda-offering-up-to-8000-off-the-prologue-ev/","title":"Honda Offering Up To $8,000 Off The Prologue EV!","summary":"EV demand declines after federal tax credit elimination; Honda implements substantial discounts to maintain sales.","source_name":"CleanTechnica","domain":"cleantechnica.com","published_at":"2026-04-07T03:53:28Z"},
    {"url":"https://cleantechnica.com/2026/04/06/why-teslas-stock-price-has-dropped-nearly-20-in-6-months/","title":"Why Tesla's Stock Price Has Dropped Nearly 20% In 6 Months","summary":"Tesla's stock experiences sustained decline reflecting broader market pressures and competitive challenges.","source_name":"CleanTechnica","domain":"cleantechnica.com","published_at":"2026-04-07T03:50:35Z"},
    {"url":"https://cleantechnica.com/2026/04/06/in-china-for-china-4-world-premieres-and-the-latest-ai-powered-systems-make-their-debut-at-the-volkswagen-group-night-in-beijing/","title":"In China, for China: 4 World Premieres at Volkswagen Group Night in Beijing","summary":"Volkswagen Group unveils ten electric models from multiple brands at Beijing auto show with AI integration.","source_name":"CleanTechnica","domain":"cleantechnica.com","published_at":"2026-04-07T03:32:16Z"},
    {"url":"https://cleantechnica.com/2026/04/06/kia-ev-sales-holding-up-okay-in-2026-in-usa/","title":"Kia EV Sales Holding Up Okay In 2026 In USA","summary":"Kia's EV lineup demonstrates resilience in the challenging 2026 US market compared to struggling competitors.","source_name":"CleanTechnica","domain":"cleantechnica.com","published_at":"2026-04-07T02:56:15Z"},
    # Carbon Brief
    {"url":"https://www.carbonbrief.org/analysis-how-chinese-media-is-covering-the-iran-energy-crisis/","title":"Analysis: How Chinese media is covering the Iran energy crisis","summary":"Examines how Chinese news outlets have covered the Iran war's energy implications, highlighting both clean energy narratives and emphasis on coal's role in energy security.","source_name":"Carbon Brief","domain":"carbonbrief.org","published_at":"2026-04-07T13:56:48Z"},
    {"url":"https://www.carbonbrief.org/introducing-carbon-briefs-2026-cohort-of-contributing-editors/","title":"Introducing Carbon Brief's 2026 cohort of contributing editors","summary":"Presents nine international academics serving as contributing editors for climate science, energy, and policy expertise.","source_name":"Carbon Brief","domain":"carbonbrief.org","published_at":"2026-04-07T09:00:00Z"},
    {"url":"https://www.carbonbrief.org/debriefed-2-april-2026/","title":"DeBriefed 2 April 2026: Countries revive energy-crisis measures","summary":"Weekly climate briefing covering EU energy measures, UK renewable records, and analysis showing plug-in solar could save households.","source_name":"Carbon Brief","domain":"carbonbrief.org","published_at":"2026-04-02T15:32:06Z"},
    {"url":"https://www.carbonbrief.org/analysis-record-wind-and-solar-saved-uk-from-gas-imports-worth-1bn-in-march-2026/","title":"Record wind and solar saved UK from gas imports worth 1bn in March 2026","summary":"March 2026 set records for combined wind and solar generation, avoiding approximately 1 billion in gas imports.","source_name":"Carbon Brief","domain":"carbonbrief.org","published_at":"2026-04-02T14:25:28Z"},
    {"url":"https://www.carbonbrief.org/china-briefing-2-april-2026-ev-profits-rise-ming-yang-rejected-iran-war/","title":"China Briefing 2 April 2026: EV profits rise, Ming Yang rejected, Iran war","summary":"Covers Chinese electric vehicle profitability trends, UK rejection of Ming Yang's wind turbine factory investment.","source_name":"Carbon Brief","domain":"carbonbrief.org","published_at":"2026-04-02T14:04:54Z"},
    # PV Magazine Global
    {"url":"https://www.pv-magazine.com/2026/04/07/microinverters-hacked-with-ai-coordinated-remote-shutdown-possible/","title":"AI-enabled hacks expose remote shutdown risk in microinverters","summary":"Security researchers identified a critical vulnerability in AP Systems microinverters that could enable coordinated shutdown of tens of thousands of devices.","source_name":"PV Magazine Global","domain":"pv-magazine.com","published_at":"2026-04-07T15:50:59Z"},
    {"url":"https://www.pv-magazine.com/2026/04/07/greek-utility-completes-2-13-gw-solar-cluster-at-former-coal-mine/","title":"Greek utility completes 2.13 GW solar cluster at former coal mine","summary":"Greece's PPC Group finished constructing a 2.13 GW solar portfolio on former lignite mining sites.","source_name":"PV Magazine Global","domain":"pv-magazine.com","published_at":"2026-04-07T13:49:08Z"},
    {"url":"https://www.pv-magazine.com/2026/04/07/greece-installs-1-9-gw-of-pv-capacity-in-2025/","title":"Greece installs 1.9 GW of PV capacity in 2025","summary":"Greece deployed approximately 1.9 GW of new solar capacity in 2025, bringing cumulative installed capacity to roughly 11.5 GW.","source_name":"PV Magazine Global","domain":"pv-magazine.com","published_at":"2026-04-07T13:30:55Z"},
    {"url":"https://www.pv-magazine.com/2026/04/07/aroma-solar-launches-1-2-gw-module-factory-in-india/","title":"Aroma Solar launches 1.2 GW module factory in India","summary":"Aroma Solar opened a fully automated TOPCon module manufacturing facility in northern India.","source_name":"PV Magazine Global","domain":"pv-magazine.com","published_at":"2026-04-07T12:30:12Z"},
    {"url":"https://www.pv-magazine.com/2026/04/07/cornex-unveils-new-165-ah-sodium-ion-prismatic-cell-for-stationary-energy-storage/","title":"Cornex unveils new 165 Ah sodium-ion prismatic cell for stationary energy storage","summary":"Chinese battery manufacturer Cornex announced a new sodium-ion cell offering improved competitiveness for large-scale energy storage.","source_name":"PV Magazine Global","domain":"pv-magazine.com","published_at":"2026-04-07T11:24:11Z"},
    {"url":"https://www.pv-magazine.com/2026/04/07/the-hydrogen-stream-dutch-electrolyzer-merger-forms-alquion/","title":"The Hydrogen Stream: Dutch electrolyzer merger forms Alquion","summary":"Battolyser Systems and VDL Hydrogen Systems merged to form Alquion; Ming Yang plans investments in Ethiopia.","source_name":"PV Magazine Global","domain":"pv-magazine.com","published_at":"2026-04-07T11:00:35Z"},
    {"url":"https://www.pv-magazine.com/2026/04/07/austrian-manufacturer-debuts-air-to-water-propane-heat-pump-series/","title":"Austrian manufacturer offers modular air-to-water propane heat pumps","summary":"Lambda heat pump series delivers over 30% lower electricity consumption compared to A+++ standard systems.","source_name":"PV Magazine Global","domain":"pv-magazine.com","published_at":"2026-04-07T08:37:53Z"},
    {"url":"https://www.pv-magazine.com/2026/04/07/croatia-tenders-56-mw-solar-storage-project/","title":"Croatia tenders 56 MW solar-storage project","summary":"Croatian utility HEP is seeking bidders for a 56 MW solar project paired with up to 200 MWh of battery storage.","source_name":"PV Magazine Global","domain":"pv-magazine.com","published_at":"2026-04-07T08:29:06Z"},
    {"url":"https://www.pv-magazine.com/2026/04/07/gcl-optoelectronic-targets-2026-ipo-us-plant-space-solar-rollout/","title":"GCL Optoelectronic targets 2026 IPO, US plant, space solar rollout","summary":"GCL Technology plans a Hong Kong IPO for its perovskite subsidiary, alongside potential U.S. expansion and space-based solar.","source_name":"PV Magazine Global","domain":"pv-magazine.com","published_at":"2026-04-07T08:15:40Z"},
    {"url":"https://www.pv-magazine.com/2026/04/07/pv-driven-hydraulic-hydro-storage-may-hit-0-022-kwh-lcoe-in-the-u-s/","title":"PV-driven hydraulic hydro storage may hit $0.022/kWh LCOE in the U.S.","summary":"Utility-scale solar paired with gravity-based hydraulic hydro storage could achieve LCOE as low as $0.022/kWh.","source_name":"PV Magazine Global","domain":"pv-magazine.com","published_at":"2026-04-07T07:30:53Z"},
    # Energy Storage News
    {"url":"https://www.energy-storage.news/co2-battery-startup-energy-dome-signs-mou-to-deploy-technology-at-texas-data-centre/","title":"CO2 battery startup Energy Dome signs MOU to deploy technology at Texas data centre","summary":"Energy Dome and New Era Energy & Digital have signed an MOU to deploy CO2 Battery Plus technology in Odessa, Texas.","source_name":"Energy Storage News","domain":"energy-storage.news","published_at":"2026-04-07T12:19:58Z"},
    {"url":"https://www.energy-storage.news/boralex-six-nations-of-the-grand-river-secure-us145-million-financing-for-500mwh-ontario-bess/","title":"Boralex, Six Nations secure US$145M financing for 500MWh Ontario BESS","summary":"Boralex and Six Nations closed CA$202 million in financing for a 125MW/500MWh battery storage project in Ontario.","source_name":"Energy Storage News","domain":"energy-storage.news","published_at":"2026-04-07T11:59:03Z"},
    {"url":"https://www.energy-storage.news/north-dakota-approves-certificate-of-site-compatibility-for-400mwh-bess-from-nextera-energy-resources/","title":"North Dakota approves certificate for 400MWh BESS from NextEra","summary":"North Dakota approved NextEra's 400MWh battery storage project representing a US$128.6M investment.","source_name":"Energy Storage News","domain":"energy-storage.news","published_at":"2026-04-07T11:51:45Z"},
    {"url":"https://www.energy-storage.news/catl-envision-sodium-ion-bess-cells-among-next-gen-tech-and-solutions-showcased-at-beijing-expo-esie-2026/","title":"CATL, Envision sodium-ion BESS cells showcased at Beijing expo ESIE 2026","summary":"Major energy storage firms unveiled sodium-ion products, integrated solutions, and data centre offerings at Beijing expo.","source_name":"Energy Storage News","domain":"energy-storage.news","published_at":"2026-04-07T11:45:24Z"},
    {"url":"https://www.energy-storage.news/neoen-enlists-nidec-for-496mwh-france-bess-launches-japan-project/","title":"Neoen enlists Nidec for 496MWh France BESS, launches Japan project","summary":"IPP Neoen will begin construction on utility-scale battery storage projects in France and Japan.","source_name":"Energy Storage News","domain":"energy-storage.news","published_at":"2026-04-07T10:04:52Z"},
    # PV Tech
    {"url":"https://www.pv-tech.org/us-federal-permitting-delays-drive-cost-of-renewable-energy-deployment/","title":"Federal permitting delays in the US could drive cost of renewable energy deployment up by 10%","summary":"Federal permitting delays have held up 11GW of new renewable energy deployment in the US in the last year.","source_name":"PV Tech","domain":"pv-tech.org","published_at":"2026-04-07T16:01:31Z"},
    {"url":"https://www.pv-tech.org/ppc-group-completes-construction-2-1gw-greek-solar-pv-portfolio/","title":"PPC Group completes construction at 2.1GW Greek solar PV portfolio","summary":"The PPC Group completed construction of a 2.13GW solar PV portfolio in Greece, the largest cluster in Europe.","source_name":"PV Tech","domain":"pv-tech.org","published_at":"2026-04-07T15:02:52Z"},
    {"url":"https://www.pv-tech.org/waaree-energies-subsidiary-commissions-3gw-pv-module-plant-in-gujarat/","title":"Waaree Energies subsidiary commissions 3GW PV module plant in Gujarat","summary":"Sangam Solar One commissioned a 3GW module manufacturing facility in Gujarat, India.","source_name":"PV Tech","domain":"pv-tech.org","published_at":"2026-04-07T14:14:19Z"},
    {"url":"https://www.pv-tech.org/geronimo-power-starts-operations-at-117mw-ohio-solar-pv-plant/","title":"Geronimo Power starts operations at 117MW Ohio solar PV plant","summary":"US independent power producer Geronimo Power began operations at a 117MW solar PV project in Ohio.","source_name":"PV Tech","domain":"pv-tech.org","published_at":"2026-04-07T13:05:52Z"},
    {"url":"https://www.pv-tech.org/solar-plus-storage-could-meet-90-of-indias-power-demand-ember/","title":"Solar-plus-storage could meet 90% of India's power demand - Ember","summary":"Solar-plus-storage could supply up to 90% of India's electricity demand at a levelised cost of INR5.06/kWh.","source_name":"PV Tech","domain":"pv-tech.org","published_at":"2026-04-07T11:08:14Z"},
    {"url":"https://www.pv-tech.org/south-korea-almost-triple-renewable-energy-capacity-100gw-2030/","title":"South Korea to almost triple renewable energy capacity to 100GW by 2030","summary":"South Korea plans to increase operational renewable energy capacity from 37GW to 100GW by end of decade.","source_name":"PV Tech","domain":"pv-tech.org","published_at":"2026-04-07T11:04:23Z"},
    # RenewEconomy
    {"url":"https://reneweconomy.com.au/contentious-solar-project-scrapped-after-work-fails-to-start-on-time/","title":"Contentious solar project scrapped after work fails to start on time","summary":"A contentious solar project has been abandoned after changing ownership and missing its deadline.","source_name":"RenewEconomy","domain":"reneweconomy.com.au","published_at":"2026-04-07T06:36:34Z"},
    {"url":"https://reneweconomy.com.au/coal-to-liquids-coalitions-latest-energy-brain-fart-is-their-craziest-yet-and-that-takes-some-doing/","title":"Coal to liquids: Coalition's latest energy proposal","summary":"The Coalition proposed converting coal into liquid fuels, but cleaner solutions already exist.","source_name":"RenewEconomy","domain":"reneweconomy.com.au","published_at":"2026-04-07T04:15:48Z"},
    {"url":"https://reneweconomy.com.au/local-council-seeks-annual-100000-per-road-maintenance-fee-from-wind-and-solar-developers/","title":"Local council seeks annual $100,000 road maintenance fee from wind and solar developers","summary":"A Queensland council wants developers to contribute to road maintenance through annual funding.","source_name":"RenewEconomy","domain":"reneweconomy.com.au","published_at":"2026-04-07T03:56:29Z"},
    {"url":"https://reneweconomy.com.au/home-batteries-get-bigger-and-bigger-as-race-to-beat-rebate-changes-sparks-last-ditch-frenzy/","title":"Home batteries get bigger as race to beat rebate changes sparks frenzy","summary":"Uptake of the Cheaper Home Batteries rebate has accelerated, with installations breaking records.","source_name":"RenewEconomy","domain":"reneweconomy.com.au","published_at":"2026-04-07T03:38:55Z"},
    {"url":"https://reneweconomy.com.au/bill-shock-the-up-to-420-price-gap-between-median-electricity-plans-and-lowest-deals-on-offer/","title":"Bill shock: The up to $420 price gap between median electricity plans and lowest deals","summary":"Substantial annual savings are possible when households compare electricity plans.","source_name":"RenewEconomy","domain":"reneweconomy.com.au","published_at":"2026-04-07T01:25:58Z"},
    # Clean Energy Wire
    {"url":"https://www.cleanenergywire.org/news/special-dispatch-hungary-russian-energy-and-battery-scandals-heart-landmark-election","title":"Special Dispatch from Hungary: Russian energy, battery scandals at heart of landmark election","summary":"Analysis of Hungary's April 12 parliamentary election focusing on energy geopolitics and Russian energy dependency.","source_name":"Clean Energy Wire","domain":"cleanenergywire.org","published_at":"2026-04-01T14:58:47Z"},
    {"url":"https://www.cleanenergywire.org/factsheets/clew-guide-hungary-energy-transition","title":"CLEW Guide: Hungary sees solar boom but remains dependent on Russian energy","summary":"Comprehensive guide covering Hungary's energy transition, highlighting rapid solar expansion alongside Russian gas reliance.","source_name":"Clean Energy Wire","domain":"cleanenergywire.org","published_at":"2026-03-31T09:35:41Z"},
    # Energy Monitor
    {"url":"https://www.energymonitor.ai/news/south-korea-renewable-power-goal/","title":"South Korea sets 20% renewable power goal for 2030","summary":"The nation targets raising renewable energy to represent at least one-fifth of electricity generation within four years.","source_name":"Energy Monitor","domain":"energymonitor.ai","published_at":"2026-04-07T07:54:04Z"},
    {"url":"https://www.energymonitor.ai/news/geronimo-power-operations-solar-project-ohio/","title":"Geronimo Power begins operations at 117MW solar project in Ohio","summary":"Commercial operations commenced at the Dodson Creek Solar Project in Highland County.","source_name":"Energy Monitor","domain":"energymonitor.ai","published_at":"2026-04-06T07:24:26Z"},
    {"url":"https://www.energymonitor.ai/news/zambia-launches-solar-pv-tender/","title":"Zambia launches 300MW solar PV tender through CFIP scheme","summary":"A call for proposals opened for photovoltaic installations with combined capacity reaching 300 megawatts.","source_name":"Energy Monitor","domain":"energymonitor.ai","published_at":"2026-04-02T07:39:08Z"},
    # Dialogue Earth
    {"url":"https://dialogue.earth/en/climate/can-africa-stay-at-the-table-after-its-first-g20-presidency/","title":"Can Africa stay at the table after its first G20 presidency?","summary":"South Africa's G20 presidency advanced African priorities on energy transition and critical minerals.","source_name":"China Dialogue Energy","domain":"dialogue.earth","published_at":"2026-04-07T11:14:51Z"},
    {"url":"https://dialogue.earth/en/energy/qa-if-you-are-in-the-business-of-peace-you-must-talk-to-those-who-are-at-war/","title":"Q&A: IAEA director discusses nuclear diplomacy amid Iran tensions","summary":"The IAEA director discusses nuclear diplomacy amid escalating Iran tensions and engagement with adversaries.","source_name":"China Dialogue Energy","domain":"dialogue.earth","published_at":"2026-04-07T11:07:03Z"},
    # Renewable Energy World
    {"url":"https://www.renewableenergyworld.com/power-grid/grid-modernization/how-utilities-are-rethinking-resiliency-with-ai-planning-tools/","title":"How utilities are rethinking resiliency with AI planning tools","summary":"Rhizome CEO discusses how utilities shift toward proactive, data-driven approaches to address climate threats.","source_name":"Renewable Energy World","domain":"renewableenergyworld.com","published_at":"2026-03-31T11:00:00Z"},
    {"url":"https://www.renewableenergyworld.com/energy-storage/battery/form-energy-and-crusoe-reach-deal-for-12-gwh-of-ai-data-center-batteries/","title":"Form Energy and Crusoe reach deal for 12 GWh of AI data center batteries","summary":"Companies announced an agreement delivering 12 gigawatt-hours of energy storage for AI infrastructure beginning 2027.","source_name":"Renewable Energy World","domain":"renewableenergyworld.com","published_at":"2026-03-26T19:01:36Z"},
]

inserted = 0
errors = 0

for a in articles:
    a["fetched_at"] = NOW
    try:
        result = subprocess.run(
            ["python3", DB, "insert-article", json.dumps(a)],
            capture_output=True, text=True, timeout=10
        )
        if result.returncode != 0:
            print(f"ERROR inserting {a['url'][:60]}: {result.stderr.strip()}", file=sys.stderr)
            errors += 1
            continue

        # Mark URL as seen
        subprocess.run(
            ["python3", DB, "mark-url-seen", a["url"], "scout_retrieval"],
            capture_output=True, text=True, timeout=10
        )
        inserted += 1
    except Exception as e:
        print(f"EXCEPTION for {a['url'][:60]}: {e}", file=sys.stderr)
        errors += 1

print(json.dumps({"inserted": inserted, "errors": errors, "total": len(articles)}))
